### ISSUE TITLE
Integrating with another prom-client

### ISSUE THREAD

**Issue by DataTables** [UNIwise/socket.io-prometheus-metrics#11]
The documentation notes how you can get the metrics to serve them up using `ioMetrics.register.metrics();` which is really useful - but is it possible to use those metrics with another prom-client (specifically `express-prom-bundle` in this case, but I think it applies in general), or would I need another end point with Prometheus scraping two routes from my app (http and socket metrics)?

**Comment by naueramant** [comment]
Well that really depends on what express-prom-bundle can do. The metrics() really just returns the plain metrics which can then be served as you please.

The easy solution would be to just serve two metric endpoints. If you really want to combine them i think you might have to manually merge the express metrics with the socket io metrics?

I might look into making the register configurable in v2.
