### ISSUE TITLE
Dist directory is not in v2

### ISSUE THREAD

**Issue by DataTables** [UNIwise/socket.io-prometheus-metrics#15]
In the v2 branch's package.json there is:

```
  "main": "./dist/index.js",
  "typings": "./dist/index.d.ts",**
```

But in the .gitignore there is:

```
dist/
```

So it isn't possible to build a package that uses this branch.

**Comment by naueramant** [comment]
`dist/` should not be in version control. the `main` and `typings` fields in package.json is also meta used when you install this package as an external dependency. 

Closing the issue
