### ISSUE TITLE
Update to support socket.io v3

### ISSUE THREAD

**Issue by grahammcculloch** [UNIwise/socket.io-prometheus-metrics#17]
`socket.io` v3 was [released recently](https://github.com/socketio/socket.io/blob/master/CHANGELOG.md#300-2020-11-05). It would be great if `socket.io-prometheus-metrics` was updated to support it.

**Comment by naueramant** [comment]
I am preparing for a major version 2 of this project. I can try to look into v3 and backward compatibility.

**Comment by CrioDo** [comment]
Hi @naueramant, are there any updates on this?

**Comment by anaskhan96** [comment]
Hi @naueramant, are there any updates on this?

**Comment by DataTables** [comment]
I was just looking at this as well - you might need [this issue](https://github.com/socketio/socket.io/issues/3911) to be fixed first to get the namespaces since they are now private in SocketIO 3+.

**Comment by rafaferry** [comment]
+1! 
I'm also want to use this lib with socket.io v3

**Comment by naueramant** [comment]
There seems to be an increasing interest in this so I will allocate some time for it soon.

**Comment by naueramant** [comment]
> I was just looking at this as well - you might need [this issue](https://github.com/socketio/socket.io/issues/3911) to be fixed first to get the namespaces since they are now private in SocketIO 3+.

Thanks for the information 🙂

**Comment by okunishinishi** [comment]
any update?

**Comment by naueramant** [comment]
@okunishinishi sorry for the low level of activity in here. I really don't have any time to allocate to this right now and as of now UNIwise don't need the features of v3 so we are not going to add the support right now.

Feel free to continue the work on the `v2` branch or fork the repository and add the support.
