### ISSUE TITLE
socket_io_transmit_bytes counter doesn't change

### ISSUE THREAD

**Issue by iangregsondev** [UNIwise/socket.io-prometheus-metrics#2]
HI,

I have been using your library, works great but there is 1 metrics thats not being updated. Its the 

> socket_io_transmit_bytes counter

I am emitting things to a room that the client joins. But the counter doesn't increase.

Here is an abstract of what I am getting, as you can see the receive bytes work fine.

Maybe the library isn't listening to room emits ?

Any ideas ?

> # TYPE socket_io_events_sent_total counter
> 
> # HELP socket_io_recieve_bytes Total socket.io bytes recieved
> # TYPE socket_io_recieve_bytes counter
> socket_io_recieve_bytes{event="AUTHENTICATE"} 10194516
> socket_io_recieve_bytes{event="JOIN_CHANNEL"} 235065
> socket_io_recieve_bytes{event="SEND_EXCHANGE_RATES"} 0
> 
> # HELP socket_io_transmit_bytes Total socket.io bytes transmitted
> # TYPE socket_io_transmit_bytes counter

**Comment by naueramant** [comment]
I must admit i haven't tested it with rooms so you might be right about it not listening to room emits. If you have a fix feel free to make a pull request or else i can look into it as soon as i can :).
