### ISSUE TITLE
Found a small misspelling

### ISSUE THREAD

**Issue by sweethoneybee** [UNIwise/socket.io-prometheus-metrics#8]
Hi. I found a small misspelling at prometheus metric name.
`socket_io_recieve_bytes` misspells receive.
I think it can be confused with another metric name, `socket_io_events_received_total`, when using promQL.

**Comment by naueramant** [comment]
I will do a refactor of the project a prepare for a v2 [UNIwise/socket.io-prometheus-metrics/tree/v2](https://github.com/UNIwise/socket.io-prometheus-metrics/tree/v2)

**Comment by naueramant** [comment]
Closing since it will be fixed in v2, thanks for you feedback!
